# -*- coding: utf-8 -*-
"""assign1-3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BHBg8HV8g452K1Fqq_TaclxGPY6igIQl
"""
# Name: Dierra Martin
# Due Date: 30/8/2024
# Assignment: M1 Assign 1
# Problem Number: 3

# importing sys
import sys

# Ensure the correct number of arguments is provided
if len(sys.argv) != 4:
    print("Usage: python script.py <Name> <Height (inches)> <Weight (pounds)>")
    sys.exit(1)

# Get the input name, height, and weight from command-line arguments
name = sys.argv[1]
height = int(sys.argv[2])
weight = int(sys.argv[3])

# Calculate BMI
bmi = (weight / (height * height)) * 703

# Format BMI with 2 decimal places
bmi = round(bmi, 2)

# Print the output
print(f"{name}'s BMI is {bmi}")
